'use client';
import {useEffect,useMemo,useState} from 'react';
import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,PieChart,Pie,Cell,LabelList} from 'recharts';
import {getKas,getKasDetail,getJimpitan} from '../lib/api';

type Row={tahun:number;bulan:string;kategori:string;keterangan?:string;tipe:string;total:number;tanggal?:string|null};
const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);

export default function Dashboard({kind}:{kind:'kas'|'jimpitan'}){
 const [rows,setRows]=useState<Row[]>([]); const [detailRows,setDetailRows]=useState<Row[]>([]); const [years,setYears]=useState<number[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [mode,setMode]=useState('all'); const [year,setYear]=useState(new Date().getFullYear()); const [month,setMonth]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(10);
 useEffect(()=>{setLoading(true);setError('');(kind==='kas'?getKas():getJimpitan).then(async d=>{setRows(d?.rows??[]);setYears(d?.years??[]); if(kind==='kas'){const x=await getKasDetail();setDetailRows(x?.rows??[])}}).catch(e=>setError(e.message||'Gagal mengambil data')).finally(()=>setLoading(false))},[kind]);
 const filtered=useMemo(()=>rows.filter(r=>{if(mode==='all')return true;if(mode==='month')return r.tahun===year&&r.bulan===month;if(mode==='range'){const a=months.indexOf(from.split('-')[1]||'');const b=months.indexOf(to.split('-')[1]||'');const ay=Number(from.split('-')[0]),by=Number(to.split('-')[0]);if(!ay||!by)return true;const v=r.tahun*12+months.indexOf(r.bulan),lo=ay*12+a,hi=by*12+b;return v>=lo&&v<=hi}return true}),[rows,mode,year,month,from,to]);
 const summary=useMemo(()=>{let awal=0,masuk=0,keluar=0;filtered.forEach(r=>{if(r.tipe==='SALDO AWAL')awal+=r.total;else if(r.tipe==='PEMASUKAN')masuk+=r.total;else if(r.tipe==='PENGELUARAN')keluar+=r.total});return {awal,masuk,keluar,saldo:awal+masuk-keluar}},[filtered]);
 const cat=useMemo(()=>{const m=new Map<string,number>();filtered.forEach(r=>{if(r.tipe!=='SALDO AWAL')m.set(r.kategori,(m.get(r.kategori)||0)+r.total)});return [...m].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)},[filtered]);
 const monthly=useMemo(()=>{const m=new Map<string,{masuk:number;keluar:number}>();filtered.forEach(r=>{const k=`${r.tahun}-${r.bulan}`;const x=m.get(k)||{masuk:0,keluar:0};if(r.tipe==='PEMASUKAN')x.masuk+=r.total;if(r.tipe==='PENGELUARAN')x.keluar+=r.total;m.set(k,x)});return [...m].map(([key,v])=>({name:key,...v})).sort((a,b)=>a.name.localeCompare(b.name))},[filtered]);
 const pie=[{name:'Pemasukan',value:summary.masuk},{name:'Pengeluaran',value:summary.keluar}].filter(x=>x.value>0);
 const detailFiltered=useMemo(()=>{if(kind==='jimpitan') return filtered; return detailRows.filter(r=>{if(mode==='all')return true; if(mode==='month') return r.bulan===month; return true})},[detailRows,kind,mode,month]); const pages=Math.max(1,Math.ceil(detailFiltered.length/pageSize)); const table=detailFiltered.slice((page-1)*pageSize,page*pageSize); useEffect(()=>setPage(1),[mode,year,month,from,to,pageSize]);
 if(loading)return <div>Memuat data...</div>;
 return <>
  <div className="header"><div><div className="title">{kind==='kas'?'Dashboard Kas RT':'Dashboard Jimpitan'}</div><div className="subtitle">Rekap data dari Google Sheets</div></div></div>
  <div className="filters"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="all">Sepanjang Waktu</option><option value="month">Per Bulan</option><option value="range">Range Bulan</option></select>{mode==='month'&&<><select value={year} onChange={e=>setYear(Number(e.target.value))}>{years.map(y=><option key={y}>{y}</option>)}</select><select value={month} onChange={e=>setMonth(e.target.value)}><option value="">Pilih Bulan</option>{months.map(m=><option key={m}>{m}</option>)}</select></>}{mode==='range'&&<><select value={from} onChange={e=>setFrom(e.target.value)}><option value="">Dari Bulan</option>{years.flatMap(y=>months.map(m=><option key={`f-${y}-${m}`} value={`${y}-${m}`}>{m} {y}</option>))}</select><select value={to} onChange={e=>setTo(e.target.value)}><option value="">Sampai Bulan</option>{years.flatMap(y=>months.map(m=><option key={`t-${y}-${m}`} value={`${y}-${m}`}>{m} {y}</option>))}</select></>}</div>
  {error&&<div className="panel" style={{marginBottom:18,color:'#b42318'}}>Error: {error}</div>}
  <div className="cards"><Card label="Saldo Awal" value={summary.awal}/><Card label="Total Pemasukan" value={summary.masuk}/><Card label="Total Pengeluaran" value={summary.keluar}/><Card label="Saldo Saat Ini" value={summary.saldo}/></div>
  <div className="grid"><Panel title="Pemasukan vs Pengeluaran"><div style={{height:300}}>{pie.length?<ResponsiveContainer><PieChart><Pie data={pie} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={95} label={({name,percent})=>`${name} ${((percent||0)*100).toFixed(0)}%`}><Cell/><Cell/></Pie><Tooltip formatter={(v)=>money(Number(v))}/><Legend/></PieChart></ResponsiveContainer>:<div className="empty">Belum ada data</div>}</div></Panel><Panel title="Rekap per Kategori"><div style={{height:300}}>{cat.length?<ResponsiveContainer><BarChart data={cat} layout="vertical" margin={{left:15,right:30}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" tickFormatter={(v)=>new Intl.NumberFormat('id-ID',{notation:'compact'}).format(v)}/><YAxis type="category" dataKey="name" width={130}/><Tooltip formatter={(v)=>money(Number(v))}/><Bar dataKey="value"><LabelList dataKey="value" position="right" formatter={(v)=>money(Number(v))}/></Bar></BarChart></ResponsiveContainer>:<div className="empty">Belum ada data</div>}</div></Panel></div>
  <Panel title="Pemasukan & Pengeluaran per Bulan"><div style={{height:330}}>{monthly.length?<ResponsiveContainer><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis tickFormatter={(v)=>new Intl.NumberFormat('id-ID',{notation:'compact'}).format(v)}/><Tooltip formatter={(v)=>money(Number(v))}/><Legend/><Bar dataKey="masuk" name="Pemasukan"><LabelList dataKey="masuk" position="top" formatter={(v)=>money(Number(v))}/></Bar><Bar dataKey="keluar" name="Pengeluaran"><LabelList dataKey="keluar" position="top" formatter={(v)=>money(Number(v))}/></Bar></BarChart></ResponsiveContainer>:<div className="empty">Belum ada data</div>}</div></Panel>
  <div style={{height:18}}/>
  <Panel title={`Detail ${kind==='kas'?'Kas RT':'Jimpitan'}`}><div className="table-wrap"><table className="table"><thead><tr>{kind==='jimpitan'&&<th>Tanggal</th>}<th>Tahun</th><th>Bulan</th><th>Kategori</th>{kind==='jimpitan'&&<th>Keterangan</th>}<th>Tipe</th><th>Jumlah</th></tr></thead><tbody>{table.map((r,i)=><tr key={`${r.tahun}-${r.bulan}-${r.kategori}-${i}`}>{kind==='jimpitan'&&<td>{r.tanggal||'-'}</td>}<td>{kind==='kas'?'-':(r.tahun||'-')}</td><td>{r.bulan||'-'}</td><td>{r.kategori||'-'}</td>{kind==='jimpitan'&&<td>{r.keterangan||'-'}</td>}<td>{kind==='kas'?'TRANSAKSI':(r.tipe||'-')}</td><td>{money(r.total)}</td></tr>)}{!table.length&&<tr><td colSpan={kind==='jimpitan'?7:5} className="empty">Belum ada data</td></tr>}</tbody></table></div><div className="pagination"><select value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}><option>10</option><option>20</option><option>50</option></select><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>‹</button><span style={{padding:'7px 8px'}}>Halaman {page} / {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>›</button></div></Panel>
 </>
}
function Card({label,value}:{label:string,value:number}){return <div className="card"><div className="card-label">{label}</div><div className="card-value">{money(value)}</div></div>}
function Panel({title,children}:{title:string,children:React.ReactNode}){return <div className="panel"><h3>{title}</h3>{children}</div>}
